### ISSUE TITLE
[FEATURE] - How to produce a lot of unknown topics

### ISSUE THREAD

**Issue by riritack** [majusko/pulsar-java-spring-boot-starter#247]
i want to produce a lot of unkown topics , but i cant compelete ProducerConfiguration ,how can i do this?

**Comment by riritack** [comment]
Whether **topicpatten** mode creation is supported？

**Comment by majusko** [comment]
Hey, @riritack, I'm not quite sure what you mean by `topicpatten mode`. Can you send us Pulsar docs with an explanation of how this works? We are keen to implement such a feature.

**Comment by riritack** [comment]
Maybe MY description is wrong, my consciousness is that I want to send information to different topics, but I can't specify these topics in advance, that is, I can't specify these topics in `ProducerFactory()`, I want to be able to specify a fixed format topic, This way I can send messages on a fixed topic

**Comment by majusko** [comment]
I don't think this is somehow possible in Pulsar. You need to create a connection to a specific Pulsar topic first since it's a part or connection URL. Those connections are created on the application start because otherwise, you wouldn't be able to use the Spring benefit of auto wiring using dependency injection. In case you need to create a producer after the application start you can achieve it with Pulsar Java Client.
