### ISSUE TITLE
How to set DeadLetterPolicy ?

### ISSUE THREAD

**Issue by meidea** [majusko/pulsar-java-spring-boot-starter#66]
Is there any way to modify ConsumerBuilder ？

**Comment by majusko** [comment]
Very good point. There is no option to modify this and it's using only default configurations for the ConsumerBuilder. 

This is quite a critical bug because of the default pulsar behaviour (endless retry) that might cause unpleasant behaviour of the application.
  
I will write a fix and release a patch with the option to configure the `ConsumerBuilder` asap.
